namesake/config/routes.rb
Namesake::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'home#index'

end

namesake/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

namesake/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title, :rendered_content

  default_scope order('created_at DESC')

  before_save :render_content

  private
  def render_content
    require 'redcarpet'
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    self.rendered_content = redcarpet.render self.content
  end
end

namesake/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

namesake/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@posts = Post.all
  
	respond_to do |format|
	  format.html  # index.html.erb
	  format.json  { render :json => @posts }
	end
  end
end

namesake/app/helpers/application_helper.rb
module ApplicationHelper
 def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def markdown(text)
    #rnder = RedcarpetPrettify.new(:hard_wrap => true)
    #mkdwn = Redcarpet::Markdown.new(rnder, :no_intra_emphasis => true, :fenced_code_blocks => true, :space_after_headers => true)
    mkdwn = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :no_intra_emphasis => true, :fenced_code_blocks => true, :space_after_headers => true)
    mkdwn.render(text).html_safe
  end
end

namesake/app/views/home/index.html.erb
<div class="posts">
	<% @posts.each do |post| %>
	<div class="page-header">
	  <h1><%= post.title %> <small><%= post.created_at %></small></h1>
	</div>
		<div class="post">
			<%# post.rendered_content.html_safe %>
			<%= markdown(post.content) %>
		</div>
	<% end %>
</div>

namesake/app/views/layouts/_footer.html.erb
<p>Happenings</p>

namesake/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

namesake/app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
    <li>
      <%= link_to('Administer', admin_root_path)  %>
    </li>
    <% if admin_user_signed_in? %>
      <li>
        <%= link_to('Log Out', destroy_admin_user_session_path) %>
      </li>
    <% end %>
</ul>

namesake/app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Namesake" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div>
<pre>
<code class="prettyprint java">
public class Bicycle {

    // the Bicycle class has
    // three fields
    public int cadence;
    public int gear;
    public int speed;
}</code>
</pre>
   <pre class="prettyprint">
&lt;?php
    function hw(){
        echo "Hallo World";
    }
?&gt;</pre>
        <hr>
	    <div class="footer">
	    	<%= render 'layouts/footer' %>
	    </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>